// Package message defines stable i18n message keys for engine and UI layers.
// GUI translates keys via locale files; CLI prints English fallbacks from FormatEN.
package message

// Progress message keys (install/uninstall/GC/bucket).
const (
	ProgressInstallStarting      = "progress.install.starting"
	ProgressInstallComplete        = "progress.install.complete"
	ProgressInstallCancelled       = "progress.install.cancelled"
	ProgressUninstallStarting      = "progress.uninstall.starting"
	ProgressUninstallComplete      = "progress.uninstall.complete"
	ProgressResolvingManifest      = "progress.resolve.manifest"
	ProgressPreparingDownload      = "progress.download.preparing"
	ProgressDownloading            = "progress.download.active"
	ProgressDownloadCached         = "progress.download.cached"
	ProgressDownloadComplete       = "progress.download.complete"
	ProgressLinkingFiles           = "progress.link.files"
	ProgressCreatingShims          = "progress.shim.creating"
	ProgressUpdatingCache          = "progress.index.updating"
	ProgressExtracting             = "progress.extract.files"
	ProgressExtractDecompress      = "progress.extract.decompress"
	ProgressExtractProcessing        = "progress.extract.processing"
	ProgressExtractIndexing          = "progress.extract.indexing"
	ProgressPackageInstallComplete = "progress.install.package_complete"

	GCPrepareStore              = "progress.gc.prepare_store"
	GCClearingPartials          = "progress.gc.clearing_partials"
	GCClearingSidecars          = "progress.gc.clearing_sidecars"
	GCReadingIndexRefs          = "progress.gc.reading_index_refs"
	GCIndexRefCount             = "progress.gc.index_ref_count"
	GCScanAppsStart             = "progress.gc.scan_apps_start"
	GCScanAppsEmpty             = "progress.gc.scan_apps_empty"
	GCScanAppsSkipped           = "progress.gc.scan_apps_skipped"
	GCAppsPendingScan           = "progress.gc.apps_pending_scan"
	GCBuildingStoreIndex        = "progress.gc.building_store_index"
	GCAppsEnumeratingDirs       = "progress.gc.apps_enumerating_dirs"
	GCAppsScanPlan              = "progress.gc.apps_scan_plan"
	GCScanningApp               = "progress.gc.scanning_app"
	GCScanningAppsMerged        = "progress.gc.scanning_apps_merged"
	GCAppsScanComplete          = "progress.gc.apps_scan_complete"
	GCRefsCollected             = "progress.gc.refs_collected"
	GCScanStoreStart            = "progress.gc.scan_store_start"
	GCScanningStore             = "progress.gc.scanning_store"
	GCScanStoreComplete         = "progress.gc.scan_store_complete"
	GCNoOrphans                 = "progress.gc.no_orphans"
	GCOrphansFound              = "progress.gc.orphans_found"
	GCDeletingOrphan            = "progress.gc.deleting_orphan"
	GCDeletingOrphansBatch      = "progress.gc.deleting_orphans_batch"
	GCCompleteFreed             = "progress.gc.complete_freed"
	GCCompleteNothing           = "progress.gc.complete_nothing"

	PurgePrepare        = "progress.purge.prepare"
	PurgeRemovingIndex  = "progress.purge.removing_index"
	PurgeIndexRemoved   = "progress.purge.index_removed"
	PurgeScanningFiles  = "progress.purge.scanning_files"
	PurgeScanningInstall = "progress.purge.scanning_install"
	PurgeScanningInstalls = "progress.purge.scanning_installs"
	PurgeScanningOtherInstalls = "progress.purge.scanning_other_installs"
	PurgeNoInstallScan  = "progress.purge.no_install_scan"
	PurgeCheckingRefs   = "progress.purge.checking_refs"
	PurgeDeletingFile   = "progress.purge.deleting_file"
	PurgeCompleteFreed  = "progress.purge.complete_freed"
	PurgeCompleteNothing = "progress.purge.complete_nothing"

	BucketCloning               = "progress.bucket.cloning"
	BucketUpdating              = "progress.bucket.updating"
	BucketUpdateComplete        = "progress.bucket.update_complete"
	BucketPrepareAdd            = "progress.bucket.prepare_add"
	BucketIndexRefresh          = "progress.bucket.index_refresh"
	BucketRemoving              = "progress.bucket.removing"
	BucketRemoveComplete        = "progress.bucket.remove_complete"
	BucketNoUpdates             = "progress.bucket.no_updates"
	GitPulling                  = "progress.git.pulling"

	BootstrapInnounpDetecting   = "progress.bootstrap.innounp.detecting"
	BootstrapInnounpDiscovering = "progress.bootstrap.innounp.discovering"
	BootstrapInnounpDownloading = "progress.bootstrap.innounp.downloading"
	BootstrapInnounpExtracting  = "progress.bootstrap.innounp.extracting"
	BootstrapInnounpComplete    = "progress.bootstrap.innounp.complete"

	BootstrapGitDetecting   = "progress.bootstrap.git.detecting"
	BootstrapGitDownloading = "progress.bootstrap.git.downloading"
	BootstrapGitExtracting  = "progress.bootstrap.git.extracting"
	BootstrapGitComplete    = "progress.bootstrap.git.complete"

	BootstrapSevenZipDetecting   = "progress.bootstrap.seven_zip.detecting"
	BootstrapSevenZipDownloading = "progress.bootstrap.seven_zip.downloading"
	BootstrapSevenZipExtracting  = "progress.bootstrap.seven_zip.extracting"
	BootstrapSevenZipComplete    = "progress.bootstrap.seven_zip.complete"

	BootstrapWixDetecting   = "progress.bootstrap.wix.detecting"
	BootstrapWixDiscovering = "progress.bootstrap.wix.discovering"
	BootstrapWixDownloading = "progress.bootstrap.wix.downloading"
	BootstrapWixExtracting  = "progress.bootstrap.wix.extracting"
	BootstrapWixComplete    = "progress.bootstrap.wix.complete"
)

// Doctor check IDs and detail/hint keys.
const (
	DoctorCheckGlueRoot   = "glue_root"
	DoctorCheckGit        = "git"
	DoctorCheckSevenZip   = "seven_zip"
	DoctorCheckDark       = "dark"
	DoctorCheckInnounp    = "innounp"
	DoctorCheckShimDir    = "shim_dir"
	DoctorCheckGitHub     = "github"

	DoctorGlueRootUnknown     = "doctor.glue_root.unknown"
	DoctorGlueRootNotWritable = "doctor.glue_root.not_writable"
	DoctorGitInPath           = "doctor.git.in_path"
	DoctorGitMissing          = "doctor.git.missing"
	DoctorGitWillBootstrap    = "doctor.git.will_bootstrap"
	DoctorSevenZipMissing     = "doctor.seven_zip.missing"
	DoctorSevenZipWillBootstrap = "doctor.seven_zip.will_bootstrap"
	DoctorDarkMissing         = "doctor.dark.missing"
	DoctorDarkWillBootstrap   = "doctor.dark.will_bootstrap"
	DoctorInnounpMissing      = "doctor.innounp.missing"
	DoctorInnounpWillBootstrap = "doctor.innounp.will_bootstrap"
	DoctorShimInPath          = "doctor.shim.in_path"
	DoctorShimNotInPath       = "doctor.shim.not_in_path"
	DoctorGitHubDirectOK      = "doctor.github.direct_ok"
	DoctorGitHubMirrorOK      = "doctor.github.mirror_ok"
	DoctorGitHubGitOK         = "doctor.github.git_ok"
	DoctorGitHubDirectFailed  = "doctor.github.direct_failed"
	DoctorGitHubAllFailed     = "doctor.github.all_failed"

	DoctorHintGlueRootAccess = "doctor.hint.glue_root_access"
	DoctorHintGitInstall     = "doctor.hint.git_install"
	DoctorHintSevenZip       = "doctor.hint.seven_zip"
	DoctorHintDark           = "doctor.hint.dark"
	DoctorHintInnounp        = "doctor.hint.innounp"
	DoctorHintShimPath       = "doctor.hint.shim_path"
	DoctorHintGitHubProxy    = "doctor.hint.github_proxy"
	DoctorHintGitHubMirror   = "doctor.hint.github_mirror"

	// CLI startup notes (glue initConfig); same probes as doctor, shorter wording.
	DoctorStartupGitNote      = "doctor.startup.git_note"
	DoctorStartupSevenZipNote = "doctor.startup.seven_zip_note"
)

// Error message keys.
const (
	ErrInvalidLaunchPath     = "error.launch.invalid_path"
	ErrLaunchUnsupportedType   = "error.launch.unsupported_type"
	ErrLaunchFileMissing       = "error.launch.file_missing"
	ErrLaunchNotOpenable       = "error.launch.not_openable"
	ErrLaunchInvalidRelPath    = "error.launch.invalid_rel_path"
	ErrLaunchInvalidKind       = "error.launch.invalid_kind"
	ErrUninstallProcessesOpen  = "error.uninstall.processes_running"
)
